// ANA ESPONERA GOMEZ PRACTICA TYPESCRIPT 2022

export const COLORES: Array<string> = [
    "negro", 
    "azul", 
    "marrón", 
    "gris", 
    "verde", 
    "naranja", 
    "rosa", 
    "púrpura", 
    "rojo", 
    "blanco", 
    "amarillo",
    "turquesa",
    "verde oliva", 
    "verde menta", 
    "borgoña", 
    "lavanda", 
    "magenta", 
    "salmón", 
    "cian", 
    "beige", 
    "rosado", 
    "verde oscuro", 
    "lila",
    "amarillo pálido", 
    "fucsia", 
    "mostaza",
    "ocre", 
    "trullo", 
    "malva", 
    "púrpura oscuro", 
    "verde lima", 
    "verde claro", 
    "ciruela", 
    "azul claro", 
    "melocotón", 
    "violeta", 
    "tan", 
    "granate"
]