// ANA ESPONERA GOMEZ PRACTICA TYPESCRIPT 2022

export const NAMES: Record<string, Array<string>> = {
    "femenino": [
        "MARIA CARMEN",
        "MARIA",
        "CARMEN",
        "ANA MARIA",
        "JOSEFA",
        "MARIA PILAR",
        "ISABEL",
        "LAURA",
        "MARIA DOLORES",
        "MARIA TERESA",
        "ANA",
        "CRISTINA",
        "MARTA",
        "MARIA ANGELES",
        "LUCIA",
        "FRANCISCA",
        "MARIA ISABEL",
        "MARIA JOSE",
        "ANTONIA",
        "DOLORES",
        "SARA",
        "PAULA",
        "ELENA",
        "MARIA LUISA",
        "RAQUEL",
        "ROSA MARIA",
        "PILAR",
        "MANUELA",
        "CONCEPCION",
        "MARIA JESUS",
        "MERCEDES",
        "JULIA",
        "BEATRIZ",
        "NURIA",
        "SILVIA",
        "ALBA",
        "IRENE",
        "ROSARIO",
        "JUANA",
        "TERESA",
        "PATRICIA",
        "ENCARNACION",
        "MONTSERRAT",
        "ANDREA",
        "ROCIO",
        "MONICA",
        "ALICIA",
        "MARIA MAR",
        "ROSA",
        "SONIA",
        "SANDRA",
        "MARINA",
        "ANGELA",
        "SUSANA",
        "NATALIA",
        "YOLANDA",
        "MARGARITA",
        "MARIA JOSEFA",
        "CLAUDIA",
        "SOFIA",
        "EVA",
        "CARLA",
        "MARIA ROSARIO",
        "INMACULADA",
        "MARIA MERCEDES",
        "ANA ISABEL",
        "ESTHER",
        "NOELIA",
        "VERONICA",
        "NEREA",
        "CAROLINA",
        "ANGELES",
        "DANIELA",
        "MARIA VICTORIA",
        "EVA MARIA",
        "INES",
        "MIRIAM",
        "LORENA",
        "MARIA ROSA",
        "MARIA ELENA",
        "ANA BELEN",
        "VICTORIA",
        "MARIA CONCEPCION",
        "AMPARO",
        "MARTINA",
        "MARIA ANTONIA",
        "ALEJANDRA",
        "LIDIA",
        "CATALINA",
        "CELIA",
        "MARIA NIEVES",
        "CONSUELO",
        "FATIMA",
        "OLGA",
        "AINHOA",
        "GLORIA",
        "CLARA",

    ],
    "masculino": [
        "ANTONIO",
        "MANUEL",
        "JOSE",
        "FRANCISCO",
        "DAVID",
        "JUAN",
        "JAVIER",
        "JOSE ANTONIO",
        "DANIEL",
        "JOSE LUIS",
        "FRANCISCO JAVIER",
        "CARLOS",
        "JESUS",
        "ALEJANDRO",
        "MIGUEL",
        "JOSE MANUEL",
        "RAFAEL",
        "MIGUEL ANGEL",
        "PABLO",
        "PEDRO",
        "ANGEL",
        "SERGIO",
        "JOSE MARIA",
        "FERNANDO",
        "JORGE",
        "LUIS",
        "ALBERTO",
        "ALVARO",
        "JUAN CARLOS",
        "ADRIAN",
        "DIEGO",
        "JUAN JOSE",
        "RAUL",
        "IVAN",
        "JUAN ANTONIO",
        "RUBEN",
        "ENRIQUE",
        "OSCAR",
        "RAMON",
        "ANDRES",
        "VICENTE",
        "JUAN MANUEL",
        "SANTIAGO",
        "JOAQUIN",
        "VICTOR",
        "MARIO",
        "EDUARDO",
        "ROBERTO",
        "JAIME",
        "MARCOS",
        "IGNACIO",
        "HUGO",
        "ALFONSO",
        "JORDI",
        "RICARDO",
        "SALVADOR",
        "GUILLERMO",
        "GABRIEL",
        "MARC",
        "EMILIO",
        "MOHAMED",
        "GONZALO",
        "JULIO",
        "JULIAN",
        "MARTIN",
        "TOMAS",
        "AGUSTIN",
        "NICOLAS",
        "JOSE RAMON",
        "SAMUEL",
        "ISMAEL",
        "JOAN",
        "CRISTIAN",
        "FELIX",
        "LUCAS",
        "AITOR",
        "HECTOR",
        "JUAN FRANCISCO",
        "IKER",
        "ALEX",
        "JOSE CARLOS",
        "JOSEP",
        "SEBASTIAN",
        "MARIANO",
        "CESAR",
        "ALFREDO",
        "DOMINGO",
        "JOSE ANGEL",
        "FELIPE",
        "VICTOR MANUEL",
        "RODRIGO",
        "JOSE IGNACIO",
        "MATEO",
        "LUIS MIGUEL",
        "JOSE FRANCISCO",
        "JUAN LUIS",
        "XAVIER"        
    ],
    "apellidos": [
        "GARCIA",
        "RODRIGUEZ",
        "GONZALEZ",
        "FERNANDEZ",
        "LOPEZ",
        "MARTINEZ",
        "SANCHEZ",
        "PEREZ",
        "GOMEZ",
        "MARTIN",
        "JIMENEZ",
        "HERNANDEZ",
        "RUIZ",
        "DIAZ",
        "MORENO",
        "MUÑOZ",
        "ALVAREZ",
        "ROMERO",
        "GUTIERREZ",
        "ALONSO",
        "NAVARRO",
        "TORRES",
        "DOMINGUEZ",
        "VAZQUEZ",
        "RAMOS",
        "RAMIREZ",
        "GIL",
        "SERRANO",
        "MOLINA",
        "BLANCO",
        "MORALES",
        "SUAREZ",
        "ORTEGA",
        "CASTRO",
        "DELGADO",
        "ORTIZ",
        "MARIN",
        "RUBIO",
        "NUÑEZ",
        "SANZ",
        "MEDINA",
        "IGLESIAS",
        "CASTILLO",
        "CORTES",
        "GARRIDO",
        "SANTOS",
        "GUERRERO",
        "LOZANO",
        "CANO",
        "MENDEZ",
        "CRUZ",
        "PRIETO",
        "FLORES",
        "HERRERA",
        "PEÑA",
        "LEON",
        "MARQUEZ",
        "GALLEGO",
        "CABRERA",
        "CALVO",
        "VIDAL",
        "CAMPOS",
        "VEGA",
        "REYES",
        "FUENTES",
        "CARRASCO",
        "DIEZ",
        "CABALLERO",
        "AGUILAR",
        "NIETO",
        "SANTANA",
        "PASCUAL",
        "HERRERO",
        "MONTERO",
        "GIMENEZ",
        "HIDALGO",
        "LORENZO",
        "VARGAS",
        "IBAÑEZ",
        "SANTIAGO",
        "DURAN",
        "BENITEZ",
        "FERRER",
        "ARIAS",
        "MORA",
        "CARMONA",
        "VICENTE",
        "CRESPO",
        "SOTO",
        "ROMAN",
        "ROJAS",
        "PASTOR",
        "VELASCO",
        "SAEZ",
        "PARRA",
        "MOYA",
        "BRAVO",
        "SOLER",
        "GALLARDO"
        
    ]
};